### ISSUE TITLE
internal packages should follow guidelines

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#100]
Internal packages should have the bundle name as a prefix, i.e. within the bundle `org.eclipse.smarthome.automation.core' the packages should be 'org.eclipse.smarthome.automation.core.internal` and not `org.eclipse.smarthome.automation.internal.core`.

**Comment by hristostanchev** [comment]
Dancho will fix this.

**Comment by hristostanchev** [comment]
Danhco will make it after finalise Kai contribution for custom module types.

**Comment by danchom** [comment]
done: https://github.com/marinmitev/smarthome/pull/115
