### ISSUE TITLE
Provide all module outputs as a rule context to subsequent modules

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#101]
When implementing JavascriptModuleTypes, I came across a conceptional problem:

A generic "ScriptAction" type would not have any inputs defined, but it still needs access to the outputs of modules that ran before within the same rule (so that these values can be used within the script itself). As the available outputs depend on the concrete rule and its trigger modules, there is no chance for the ScriptAction type to define suitable inputs.

My suggestion would be to provide all module outputs in general as a rule context within the Map that it passed into module handlers (i.e. in `execute(Map<String, ?> inputs)`).
Using "<moduleId>.<outputName>" as a key within the map should hopefully prevent any clashes with the inputs.

**Comment by marinmitev** [comment]
the output of the discussion today (internally in our team) is:
- we want to avoid defining new java API
- we want to use the feature of providing all possible outputs in the rule instance to a module, only if the module does not declare any inputs
- the map that is passed to ModuleHandler.execute will be used to pass the trigger outputs where the keys are triggerID.outputName

For example:
if we have a rule with 2 triggers ("trigger1" and "trigger2") of type GenericEventTrigger with 2 outputs "output1" and "output2"

the script expression for the condition is:
$trigger1.output2 == true || $trigger2.output1 == false

**Comment by kaikreuzer** [comment]
Right, this resembles my idea.

Just one question: "only if the module does not declare any inputs" - why do you think this restriction is necessary? What's the benefit of it?

**Comment by danchom** [comment]
done

**Comment by kaikreuzer** [comment]
Closing it, but note that the chosen implementation still has a conceptional problem, see https://github.com/marinmitev/smarthome/issues/118.
