### ISSUE TITLE
Event handling order for item state change event

### ISSUE THREAD

**Issue by marinmitev** [marinmitev/smarthome#102]
There are two problems (which may have one root cause):
1. the order of delivering the event to event handlers is not the same as the order in which the handlers were registered
2. when first event handler receives the event and queries the item state - the item state is not yet changed

The consequence of these two problems is that in some rules which are triggered on item state event and the rule condition checks the item state - this check fails because the item did not receive the event prior the rule trigger and rule condition actually checks the old item state

Here is a sample test code to check the event handling

```
        def eventHandler = [
            receive: { Event e ->
                logger.info("Event1: " + e.topic + " = " + e)
                logger.warn('after event1, myMotionItem.state=' + myMotionItem.getState());
            },
            getSubscribedEventTypes: {
                Sets.newHashSet(ItemStateEvent.TYPE)
            },
            getEventFilter:{ null }
        ] as EventSubscriber
        registerService(eventHandler)

///////////////////////
        def eventHandler2 = [
            receive: { Event e ->
                logger.info("Event2: " + e.topic + " = " + e)
                logger.warn('after event2, myMotionItem.state=' + myMotionItem.getState());
            },
            getSubscribedEventTypes: {
                Sets.newHashSet(ItemStateEvent.TYPE)
            },
            getEventFilter:{ null }
        ] as EventSubscriber
        registerService(eventHandler2)
///////////////////////
        def eventHandler3 = [
            receive: { Event e ->
                logger.info("Event3: " + e.topic + " = " + e)
                logger.warn('after event3, myMotionItem.state=' + myMotionItem.getState());
            },
            getSubscribedEventTypes: {
                Sets.newHashSet(ItemStateEvent.TYPE)
            },
            getEventFilter:{ null }
        ] as EventSubscriber
        registerService(eventHandler3)
///////////////////////
```

Then when event is posted
eventPublisher.post(ItemEventFactory.createStateEvent("myMotionItem", OnOffType.ON))
the messages printed are:

```
Event2: smarthome/items/myMotionItem/state = myMotionItem updated to ON
after event2, myMotionItem.state=NULL
Event1: smarthome/items/myMotionItem/state = myMotionItem updated to ON
after event1, myMotionItem.state=ON
Event3: smarthome/items/myMotionItem/state = myMotionItem updated to ON
after event3, myMotionItem.state=ON
```

**Comment by BenediktNiehues** [comment]
This was not the cause that the tests failed on my machine, but I agree, that this event handling stuff is not an real-time implementation and could fail for the case you described. But I have no idea how we should solve this problem instead of wiring outputs with inputs consequently.
Maybe we should mention this in the developer-documentation so that ModuleHandler developers are aware of this.
