### ISSUE TITLE
Ids of CustomizedModuleTypes 

### ISSUE THREAD

**Issue by BenediktNiehues** [marinmitev/smarthome#107]
I would like to have only the last part of the ID be treated as the ID of an customized moduleType. So that we can express a chain for  BaseModuleType->CutomModuleType->MoreCustomModuleType as follows:

```
"BaseModuleType": {...}

"BaseModuleType:CustomModuleType":{...}

"CustomModuleType:MoreCustomModuleType":{...}
```

The Ids of the CustomModuleTypes should be only CustomModuleType and MoreCustomModuleType then. With this approach the CustomModuleType only needs to know its direct parent as it should be in the implementation as well.
In the rule where these moduleTypes will be used, we then only should specify the ID of the CustomModuleType as well.

**Comment by kaikreuzer** [comment]
I think the main question here is where the reference to the parent module type is kept within the Java model. In JSON, your suggestion is to keep it as a part of the ID, right? (i.e. `"ParentModuleType:CustomModuleType":{...}`). But what will ModuleType.UID contain? Also `ParentModuleType:CustomModuleType` or only `CustomModuleType`? If rules refer to the module type as `CustomModuleType`, this should imho also be the ID that is used for lookup.  So either the ModuleTypeRegistry has to know that and find the module with UID `ParentModuleType:CustomModuleType` if you are actually asking for `CustomModuleType` (which is somewhat unexpected) or the ModuleType class would require some additional property for the reference to the parent module type. A straight-forward solution for adding such a reference would be to align it with #64 and simply use a CompositeModuleType, where we already allow delegation to other (parent) modules.

**Comment by marinmitev** [comment]
We had a discussion here and agreed on the idea to remove the separator ':' in the UID of custom module types and use a dedicated property "parent" to specify the system(parent) module type.

**Comment by kaikreuzer** [comment]
> use a dedicated property "parent" to specify the system(parent) module type.

Where do you want to introduce this new property? On the ModuleType class? This would imho spoil the class with stuff that is only relevant for certain implementations. I would very much prefer to have it only introduced in a subclass instead.

**Comment by marinmitev** [comment]
currently the ModuleType is abstract class which is extended by ActionType, ConditionType, TriggerType
There is also CompositeActionType which extends ActionType and CompositeConditionType extending ConditionType and CompositeTriggerType extending TriggerType
adding a new subclass(s) will not be efficient just for one property
Please note that Composite module types are not replacement for custom module types, they are containers of several instances of modules

**Comment by marinmitev** [comment]
after the latest discussions custom module types will be replaced by composite module types with only one child:
see the format for composite module types here
https://github.com/marinmitev/smarthome/issues/64#issuecomment-137757923

**Comment by kaikreuzer** [comment]
> see the format for composite module types here

One suggested change: Within the composite, could we replace the keywords "triggers/conditions/actions" simply with "children", so that it is exactly the same for all types? The type of the children is anyhow already defined by the type of the composite itself.
