### ISSUE TITLE
Getting all module types does not consider composite types

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#139]
ModuleTypeManager can return all modules by class type (getTypes(Class moduleType, Locale locale)). The issue is that if I want to get all TriggerTypes it will not return CompositeTriggerType because of the following line:

if (moduleType.getName().equals(mt.getClass().getName()))

Is it for purpose?

**Comment by hristostanchev** [comment]
I think this is a bug. Dancho can comment also.

**Comment by danchom** [comment]
It is fixed in PR #144. The getTypes(Class<T> type) must return all types which are inherited of the pass argument type.
