### ISSUE TITLE
Tests with Composite trigger "ItemStateChangeTrigger" fail

### ISSUE THREAD

**Issue by marinmitev** [marinmitev/smarthome#145]

**Comment by kaikreuzer** [comment]
@marinmitev, do the tests org.eclipse.smarthome.automation.module.core.test succeed for you?
I have 2 out of 3 still failing...

**Comment by marinmitev** [comment]
@kaikreuzer I was running only the integration tests, now I have fixed the module.core test - it was an issue in the test itself. First, not the correct event was posted for item change, then the assertion for rule status was not correct. Please check the Pull request
