### ISSUE TITLE
Fail in composite trigger

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#146]
I've defined a rule which contains composite trigger and composite condition (See below). It seems to fail on the trigger when it checks:

public void receive(Event event) {

```
 if (!event.getTopic().contains(source)) {
```

}

The source that I see is $itemName. It seems that the reference wasn't replaced with the item name: demo_switch_1_switch. Currently I cannot find in the source were the replacement is being done for composite trigger.

BTW, is it valid to define a rule without action (although I know that it doesn't make any sense).
# The rule:

[
  {
    "uid": "smart.rule.composite",
    "name": "SmartRule",
    "tags": [
      "smart",
      "rule"
    ],
    "description": "Smart Rule definition composite.",
    "on": [
      {
        "id": "SmartTriggerID",
        "type": "ItemStateChangeTrigger",
        "config": {
          "itemName": "demo_switch_1_switch"
        }
      }
    ],
    "if": [
      {
        "id": "SmartConditionID",
        "type": "ItemStateEvent_ON_Condition",
        "config": {
          "itemName": "demo_switch_1_switch"
        }
      }
    ],
    "then": [
    ]
  }
]

**Comment by kaikreuzer** [comment]
This is exactly the same that I observed with this test: https://github.com/marinmitev/smarthome/pull/143

**Comment by kaikreuzer** [comment]
@smhgit Can you confirm that this is fixed and close the issue?

**Comment by smhgit** [comment]
Sure, I can check it and update

**Comment by smhgit** [comment]
Issue is fixed
