### ISSUE TITLE
Fail composite condition

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#152]
Hi,

See rule below. It seems that it fails "to satisfy" the condition. As far as I can see, it fails in ""EventCondition" because $event gets null in the inputs (which means event is null).

``` java
 @Override
    public boolean isSatisfied(Map<String, ?> inputs) {
        Event event = inputs.get("event") != null ? (Event) inputs.get("event") : null;
        if (event != null) {
            return isConfiguredAndMatches(TOPIC, event.getTopic()) && isConfiguredAndMatches(SOURCE, event.getSource())
                    && isConfiguredAndMatches(PAYLOAD, event.getPayload())
                    && isConfiguredAndMatches(EVENTTYPE, event.getType());
        }
        return false;
    }
```
# The rule:

```
[
{
"uid": "smart.rule.composite",
"name": "SmartRule",
"tags": [
"smart",
"rule"
],
"description": "Smart Rule definition composite.",
"on": [
{
"id": "SmartTriggerID",
"type": "ItemStateChangeTrigger",
"config": {
"itemName": "demo_switch_1_switch"
}
}
],
"if": [
{
"id": "SmartConditionID",
"type": "ItemStateEvent_ON_Condition",
"config": {
"itemName": "demo_switch_1_switch"
}
}
],
"then": [
]
}
]
```

**Comment by marinmitev** [comment]
Hi @smhgit in your rule you have to connect the rule condition input  to rule trigger output using the following
        "input":{
            "event":"SmartTriggerID.event"
        }

see some example rules that we use for integration tests:
https://github.com/marinmitev/smarthome/tree/automation-component-impl/bundles/automation/org.eclipse.smarthome.automation.integration.test/ESH-INF/automation

**Comment by smhgit** [comment]
This solved my issue. I was confused because I thought that the input is already there in the composite module type:

ItemStateEvent_ON_Condition

 "input":{
            "event":{
                "type":"org.eclipse.smarthome.core.events.Event",
                "description":"the event of the item state change",
                "label":"event",
                "required":true
            }
          },

I am closing this issue,
