### ISSUE TITLE
Using '.' char in module id

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#181]
In the last pull request (#173) changes, the connection is given via Map<String, String>. The key is the input name and the value is the module id appended with '.' and output name.

The issue is that if the module id already contains the character '.' it will fail to build correct connection.

If it is not allowed to use '.' in the module id than this is not an issue, otherwise it should be addressed.

This will pass: event, demo_1.event
This will fail: event, demo.1.event

(demo.1 is the id).

The failure is here:

```
                int index = output.indexOf('.');
                if (index != -1) {
                    String outputId = output.substring(0, index);
                    outputName = output.substring(index + 1);
                    Connection connection = new Connection(inputName, outputId, outputName);
                    connections.add(connection);
                } else {
                    log.error("Wrong format of Output : " + inputName + ": " + output);
                    continue;
                }
```

**Comment by kaikreuzer** [comment]
A valid remark, which should make us clearly define the set of allowed characters. I would think it should be similar to what we have for the segments of a ThingUID, which is the same as for item names, i.e. `[A-Za-z0-9_-]*`. Any opinions?

**Comment by marinmitev** [comment]
I agree to limit the allowed characters to [A-Za-z0-9_-]\* but isn't it more correct to define the first symbol to be a letter: [A-Za-z][A-Za-z0-9_-]*

**Comment by kaikreuzer** [comment]
> isn't it more correct to define the first symbol to be a letter

I do not see any need for this constraint. I have rather seen many potential problems, because people also like to give names like "1Wire", "4All" or whatever...

**Comment by danchom** [comment]
The dot '.' is used as separator when input of a module is defined. If a dot exists in the name the rule engine will confuse in resolving module connections. I don't see why the constant to be [A-Za-z0-9_-]*

**Comment by BenediktNiehues** [comment]
the constraint is just for the moduleId and not for the value of the reference String to ensure that there is no dot in the id so that the ruleEngine will not be confused while resolving module connections. I would appreciate to be able to give my modules id's like 4All etc. as well, so [A-Za-z0-9_-]\* would be the best for me as well.

**Comment by danchom** [comment]
Add module id validation (must not contain dot) #195
