### ISSUE TITLE
ItemStateChangeTrigger not working for GroupItem?

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#182]
Hi,

I don't know if it is an issue or not.

The ItemStateChangeTrigger  defined as "This triggers a rule if an items state changed". AFAIU, group item which its state changed based on a function (or, and etc.) will not send an event if one of its items have changed state, which means that it wouldn't trigger the rule.

Is it the case? Would it be valid to use StateChangeListener as the trigger source?

**Comment by kaikreuzer** [comment]
Valid point. The GroupItem itself listens on state changes of its members (in GroupItem.stateChanged()) and recalculates its own state. It does NOT send a a change event for itself though, but only informs all StateChangeListener about it. The old (current) rule engine actually registers as such a StateChangeListener and thus is able to react on Group items even though there is no event.

So two possible options:
1. Make the new rule engine (or rather specific modules) also register as a StateChangeListener on all items and not use the events.
2. Let the Group Item publish a change event as well - it actually also has the chance to name the item that caused the state change of the group (which is a very regular feature request). To provide it, we might need a special new GroupItemStateChangeEvent type.

**Comment by danchom** [comment]
Isn't be easier to create a new TriggerType and Handler for it ?

**Comment by smhgit** [comment]
In that case, do you want to keep the trigger based on the event?

**Comment by BenediktNiehues** [comment]
I would say that this should be solved in the way Kai mentioned in approach 2. Therefore we should create a feature request for esh as this is a common use case. The first approach would affect more overhead for the trigger implementation, the Trigger itself additionally has to observe the itemRegistry at least for added Items as well...

**Comment by kaikreuzer** [comment]
I have entered https://bugs.eclipse.org/bugs/show_bug.cgi?id=481716 for this.
