### ISSUE TITLE
Add output to ItemStateEvent_OFF_Condition / ItemStateEvent_ON_Condition?

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#183]
Would it make sense to add the itemName as an output to these conditions?

I want to have the item name so I can use it in the action. I can define new module for that but I think it is something that will be use-full in general.

**Comment by smhgit** [comment]
I would like to extend the issue:

How can I get in the Action the outputs from the trigger and from the condition?

**Comment by kaikreuzer** [comment]
Afaik, the event triggers have an output called "event". This is available in the rule context that is passed into your action (as "<triggerId>.event"). An ItemStateEvent contains the itemName as well as the itemState.

**Comment by smhgit** [comment]
As far as I can see, I don't get the event in the Action.The event trigger is passed to the condition and not to the action. What I do get in the action module is the action config, but maybe I am missing something here.

Please also consider the following cases:
1. The trigger event is different from the condition. I can listen to a trigger on item A but check item B state in the condition.
2. There is a trigger and no condition. How can I get the trigger output?

**Comment by kaikreuzer** [comment]
I think all your use cases should be included in https://github.com/marinmitev/smarthome/issues/101.

**Comment by smhgit** [comment]
Yes, I can see that I get the inputs. Thx for the help!

Closing this issue.
