### ISSUE TITLE
Document module type return value of inputs / outputs

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#189]
Hi,

Currently the documentation doesn't includes what is returned if the module type doesn't have any inputs / outputs. Can you please add define what is returned in case of no inputs / outputs (null? empty set?).

As I need to check if condition match trigger I am comparing the outputs and inputs type. Currently it is not clear from the documentation if I should expect null or not.

```
/**
 * This method is used for getting the meta-information descriptions of {@link Input}s defined by this type.<br/>
 * 
 * @return a {@link Set} of {@link Input} definitions.
 */
public Set<Input> getInputs() {
    return inputs;
}

/**
 * This method is used for getting the meta-information descriptions of {@link Output}s defined by this type.<br/>
 * 
 * @return a {@link Set} of {@link Output} definitions.
 */
public Set<Output> getOutputs() {
    return outputs;
}
```

**Comment by dnobel** [comment]
Usually in ESH you can expect that every method which has a List, Set, or Array as return type you will never get null. Also most of the other interfaces don´t mention it (e.g. ItemRegistry). Only in very rare cases, where a method needs to return null, we will explicitly mention, that null can be returned.

Is that OK for you?

**Comment by smhgit** [comment]
It is OK. The issue is that as far as I can see, those functions returns null when there are no inputs / outputs and I was expecting to get empty list.

**Comment by dnobel** [comment]
> The issue is that as far as I can see, those functions returns null when there are no inputs

I hope not. But we will check it again

**Comment by danchom** [comment]
The PR #192 fixes this issue.
