### ISSUE TITLE
Rule execution priority

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#190]
Is there a way to define priority execution for rules?

**Comment by dnobel** [comment]
Why do rules need a priority? Usually a priority is needed if something is conflicting or should be processed before something else. But rules can be executed in parallel, so I don´t see a real use case here. Can you give us an example, please?

**Comment by smhgit** [comment]
After your comment and re-thinking I am not sure this is an issue or needed. I will close the issue. If I will find a use case I will reopen.

Thx
