### ISSUE TITLE
Should be possible to add a rule through the rule registry, when the rule managed provider is not available?

### ISSUE THREAD

**Issue by danchom** [marinmitev/smarthome#196]
We already have discussed that the rule registry has to work without storage (without rule managed provider) - because other rule provider can exist. 
At the moment rules can be added through rule registry interface independent of existence of rule managed provider, but we can add rule with uid which is already stored (and modified) in the managed provider, and when the managed provider become available the stored rule will not be loaded.

**Comment by BenediktNiehues** [comment]
Good point, but this behavior is the same for all managed providers in esh. First come, first serve! I don't expect so many rule providers to be active in parallel that there will be conflicts. We should be aware of this problem, but IMHO we should not try to find a solution for the final PullRequest. Maybe it is sufficient to log an error in the managedProvider if such a case will occur. 
And it should be possible to add a rule through the registry with any id. If the managed provider then is activated again and tries to add a rule with the same id to the registry, IMHO the rule stored in the managed provider should be updated with the values of the current values in the registry.

**Comment by kaikreuzer** [comment]
I agree with @BenediktNiehues and this is what we had discussed before: Although there is a risk for conflicts, this is accepted and providers should usually use a specific prefix for their rule ids, so that conflicts are unlikely.

**Comment by danchom** [comment]
I mean following scenario:
1) Rules are loaded by the RuleResourceBundleImporter and they have specific uids base on their bundle source (but not all uids are generated, some of them are set by an user). But the importer only imports rules and they are stored into RuleManageProvider.
2) User make changes on these rules and the changes are stored into managed provider.
3) Restart the system and the storage for example is not available, which means the ManagedRuleProvider is missing.
4) User adds a rule, through the rule registry, containing  uid same as a rule loaded from RuleResourceBundleImporter 
5) The ManagedRuleProvider is appeared , but it can not add rule with same uid 

I want mention that we don't have same problem between  RuleResourceBundleImporter  and RuleManageProvider, because the RuleResourceBundleImporter waits for RuleManageProvider to appear and that tries to import rules form bundle resources.

**Comment by BenediktNiehues** [comment]
@danchom you bring me to another point: What happens after a restart to a rule which initially is added by the ResourceBundleImporter and changed afterwards? Will then the original version defined in Json be loaded, or are changes kept?
I would expect, if first come first serve, and the ResourceImporter waits for ManagedProvider, the Rule with the changes is in place.

**Comment by danchom** [comment]
Yes the changed rule has to be loaded. That is the goal, we must not lose changes made by the user.

**Comment by adimova** [comment]
What must happen when the bundle providing these rules is updated with new versions of these rules?

**Comment by adimova** [comment]
I propose to modify the RuleResourceBundleImporter become RuleProvider and no waiting for ManagedRuleProvider, what is your appinion about that?

**Comment by danchom** [comment]
@Any, I think we have already discussed that the loaded rules must be explicitly removed through the rule registry before they can be updated. The reason for this is: if you made changes into loaded rules, (this change is made by the user), and a new version of bundles are appeared (this can be done by administrator), the administrator's rules will overwrite user's rules, and the user will lost his changes.

**Comment by BenediktNiehues** [comment]
Yes, do not touch a rule modified by the user! Rules imported once through the json resources should only change if they were explicitly removed before. Surely this would lead to a confusion on users side, if he/she deletes a rule via a UI and after reboot the rule appears again. Regarding this case pre-installed Rules should be handled carefully. I don't know if they are needed at all on a users installation because you never know which items are available. If you want to provide some basic rules better use Templates for it.

**Comment by adimova** [comment]
@Dancho, if someone loads rules through the bundle, do he/she expect someone else to change them through the UI and if he/she want to update them through the bundle, do he/she expect this can't happen or do he/she expect to must remove them one by one, before that can happen, through the UI? Because this is what happen now.

**Comment by danchom** [comment]
If the rules are public, yes, he/she has to expect changes. If they are private they should have set appropriate scope identity. As @BenediktNiehues said;  "do not touch a rule modified by the user".

**Comment by adimova** [comment]
the rules will never be public, do you want someone else to manage the rules in your home? that's the purpose they to have a scope identity and don't have visibility

**Comment by danchom** [comment]
When I talk about public/private rules i mean rules without/with scope identity. I understand misunderstanding with Visibility public/private.
The rules without scope identity (public ones) can be access, edit and removed by users and applications of the system. And these changes must not be lost.
