### ISSUE TITLE
Time trigger

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#197]
This is more of a question than an issue. If I want to add time trigger that it will be based on cron expression. Is the right approach will be to implement the cron handling in the trigger or do you plan to add binding (something else?) that will send events based on cron expressions?

**Comment by kaikreuzer** [comment]
I am definitely for a trigger type on its own.

**Comment by BenediktNiehues** [comment]
Yes, I am also thinking of a timer trigger type with a configuration for a cron.

**Comment by smhgit** [comment]
So the "cron engine" will be part of the timer trigger handler.

The only thing that bother me is that I would expect that a trigger will register and "listen" to system events and will transfer them to the condition. If we include cron within the trigger that means that the trigger is the one that fire events for its own use.

**Comment by kaikreuzer** [comment]
> I would expect that a trigger will register and "listen" to system events

No, this is only the case for event-based triggers. Time-based triggers also make sense beside that. In openHAB 1, we also have time and event based triggers, so this is nothing to worry about ;-)

**Comment by smhgit** [comment]
Do you plan to add such trigger in the module core?

**Comment by danchom** [comment]
I'm not sure if it has to be part of the core module types or it can be provided by separate bundle?

**Comment by kaikreuzer** [comment]
I think we should have some time-based trigger in core modules. As CRON is probably the most flexible choice, I think this would be a good option. We could then offer specialized triggers like a daily alarm at a fixed time simply as a composite module, hiding the CRON expression itself from the user in the configuration.

The main problem here might be a technical one? How to evaluate and schedule CRON jobs? In openHAB 1, we are using the Quartz library, but I am a bit reluctant to introduce that as a mandatory dependency to the rule engine. Do you have any good solution for that?

**Comment by smhgit** [comment]
An option will be to add a bundle that will be able to generate time events based on different type of expressions (One of the expression could be CRON expressions). 

The benefits I see:
1. The rule engine will not be based on Quartz.
2. Simplify the time handlers (as they just listen to events)
3. The bundle can generate pre-defined events, e.g., day event, part of day event etc.
4. You don't need to define a CRON job for each trigger.
5. I am not sure but somehow it can also have the same functionality the NTP binding have and maybe  the NTP binding can be removed.

**Comment by kaikreuzer** [comment]
I do not see how you could then easily allow using time-based conditions in a rule editor. When I want to create a rule that does something at 8am every day, what module type should I use and which configuration shall I give to it?

**Comment by danchom** [comment]
I think Quartz is not an option, because it is very fat (3 MB). I've already started to try to implement this trigger base on cron4j library. 
Here is a list of possible solutions:
http://blog.dreamcss.com/tools/java-based-job-scheduler/

**Comment by kaikreuzer** [comment]
> I think Quartz is not an option

I think we all agreed on that, yes.

> base on cron4j library

This isn't an option either since it is under LGPL, which is incompatible with EPL.

**Comment by dnobel** [comment]
> I think Quartz is not an option
> I think we all agreed on that, yes.

I don´t agree ;). What is the concrete problem with quartz? Just the size of the problem?

@kaikreuzer Do you see a Timer trigger as an essential part of the rule engine, so that we have to include it in the initial PR?

**Comment by kaikreuzer** [comment]
> Do you see a Timer trigger as an essential part of the rule engine, so that we have to include it in the initial PR?

Yes, see https://github.com/marinmitev/smarthome/issues/197#issuecomment-152268818.

> What is the concrete problem with quartz?

Just for CRON support, the size is indeed an issue. But what is worse is that I remember that Quartz caused many problems when running on OpenJDK for openHAB 1. I don't have an exact reference, but this is what I vaguely remember.

**Comment by kaikreuzer** [comment]
Ok, I have a suggestion:
ESH already contains Quartz in the core.scheduler bundle. We could simply add an optional import to those packages from the core.module bundles and only register the timer module type if this import is satisfied.

I have also checked about the size of Quartz: Currently, the core.scheduler bundle is 700KB, which isn't as bad as expected. Looking into the code, we could potentially strip down the Quartz sources to around 300KB - but we would have to fork the code as it cannot be automatically stripped (it is not just removing some packages, but also has impact on the code within required classes). This would leave us the option to have a pretty lightweight implementation in the future, it is merely a matter of effort.

**Comment by danchom** [comment]
It seems ok for us, but the core.schedule has a lot of other dependences and I'm not sure if they all are needed. We can't use this timer with all of them.
javax.transaction.source_1.1.1.v201105210645.jar
org.eclipse.equinox.transforms.hook.source_1.1.0.v20131021-1933.jar
org.eclipse.osgi.compatibility.state.source_1.0.0.v20140403-1907.jar
org.eclipse.equinox.region.source_1.2.0.v20140128-1636.jar
org.eclipse.equinox.weaving.hook.source_1.1.0.v20140529-1734.jar

**Comment by kaikreuzer** [comment]
Where do you get these dependencies from? I am pretty sure there are no dependencies on source jars.
In https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.scheduler/META-INF/MANIFEST.MF#L14, I do not see any other dependency than on org.osgi and org.slf4j...

**Comment by danchom** [comment]
I get them from eclipse plugin depandencies section of the project core.schedule

**Comment by kaikreuzer** [comment]
Well, this is what Equinox brings in order to fulfill the org.osgi dependency. You should only regard the manifest to see what the real dependencies are.
