### ISSUE TITLE
Mark core module types as system?

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#199]
I want to be able to hide from the user module types which are supplied by the module.core. Is there a way to distinguish between module types from the core to module types I generate? E.g., something like system flag?

**Comment by danchom** [comment]
ModuleType visibility property can be used for this purpose. There are public and private values (private is not supported yet), but a system value can be added too.

**Comment by smhgit** [comment]
Just to note that a combination of values should be supported. E.g., private and system.

**Comment by kaikreuzer** [comment]
I think you should not assume that "system" = "core.module" bundle.
The module types in core.module are for me the ones that are so basic that they are relevant to all ESH-based solutions. Nonetheless, different solutions can add further module types by adding their own bundles and these module types should ALSO be considered to be system modules (as it is the basic set for that solution).

What exactly is the use case you have in mind for "private" modules? Is it that they should not appear in rule editors / UIs? Then I would agree with @danchom that this is the visibility. If you want to technically constrain that some rules could not even use such modules, I think this requirement would be fundamentally different and it would require a deep integration into the rule engine.

**Comment by smhgit** [comment]
Kai, I've changed my last comment. I just don't want to show the modules in the UI. The reason is that there might be cases that I extend a module type and I don't want to show the base module type.

Adding system to visibility is a good solution. Just to note that visibility can be a combination (e.g., private and system)

**Comment by kaikreuzer** [comment]
So what is the difference between visibility "private" and "system" then? Both are not to be displayed.
I think we should anyhow rediscuss the visibility options - I would probably rather go for 3 levels like "hidden", "expert", "visible".

**Comment by danchom** [comment]
I want mention that the purpose of Visibility.private was to forbid using of this module type from all except the author of the module. Unfortunately this is not implemented yet (and I think it is not an easy task) in the rule engine. 
@smhgit if you want to extend a module type you have to create a composite module type. In your application you can show only composite module types

**Comment by kaikreuzer** [comment]
> except the author of the module

Where do we have information about the author?

**Comment by smhgit** [comment]
Using composite is an option and it might be good enough for me, but please note that I cannot hide modules which are not extended (although I must admit that currently I am not sure that this case need to be cover).

**Comment by danchom** [comment]
@kaikreuzer you are right. We don't have such information. I've confused with the rule's scope id.
@smhgit there is no way to find that a module type is extended or not. It can be extended by third party provider and after that the provider can be removed.

**Comment by kaikreuzer** [comment]
I have created https://github.com/marinmitev/smarthome/issues/214 as a follow-up.
