### ISSUE TITLE
Rule pre-defined messages

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#202]
When you use OpenHAB as the trigger in the IFTTT and Mail in the action, you get predefined Subject and Body.

E.g., the subject is: {{item}} changed to {{status}}

What I am trying to understand is how to define pre-defined messages in the action. The "ingredients" can be taken from the inputs which are passed to the action, but how to define a message that will be based on the trigger?

**Comment by kaikreuzer** [comment]
This would be clearly a configuration parameter for the action or am I missing something?

**Comment by smhgit** [comment]
If we take the mail example, the TO, SUBJECT & MESSAGE are configuration parameters. That is correct. But the issue is that I want to display to the user a pre-defined subject / message and they depends on the trigger. 

I haven't thought about how to implement it, but probably there should be a way to define messages in the trigger module type / condition module type that can be use in the action.

**Comment by danchom** [comment]
May be a new type of action has to be defined. It will convert input parameters into message and can have an output with the result message. This is an example of processor action (converter). Its output can be used by other actions send email, log, print on console and etc.

**Comment by smhgit** [comment]
Is the new type you suggest will be defined in the automation api (same as ActionType / TriggerType etc.) or it will be added to automation module core?

What I am not sure is how you can build the message just from the inputs.If we take the example: {{item}} changed to {{status}}, the item can be taken from the input but how you know you need to add "change to"?

**Comment by danchom** [comment]
It has to be just a new ActionType and it can be part of the core module. It is needed to add only json definition and handler for it. 
The pattern, which can be used for result message, will be configuration property as @kaikreuzer has proposed. The action type will define several inputs and these inputs can participated in the pattern.
In your example the pattern will be: {{input1}} changed to {{state}} or {{input1}} changed to {{input2}}, The input1 input2, and state are variables which can be get from context .

**Comment by smhgit** [comment]
So if I understand correctly for sending email we will have two actions:
1. "MessageAction"
2. MailAction

Even if it is possible from implementation POV, I am not sure it is intuitive to the user. If he has to configure two actions for mail it might be an issue.

Also please note that:
1. The user will have to select from a list of patterns although only one is actually applicable.
2. What about cases were for one action we need more than one pattern (subject and body in the mail action example).

Why not to define a pattern field in the TriggerType that can be used by the Action? I assume I can use a tag or event a parameter (which will be hidden using the advanced flag) but I am not sure this is the right approach.

**Comment by danchom** [comment]
IMHO this editing functionality is not part of rule engine and it is not needed for most of the cases. It is needed only for some message actions such as mail, log and etc and I think it must not be part of all of them , it can be extracted in separate action.

**Comment by smhgit** [comment]
I totally agree with you that the functionality is not part of the rule engine. It should be implemented in the specific action or in separate action. 

The only thing is that (in IMHO) the message is trigger type driven and this is why I suggested to add a field which will add the information that can be use by the Action.

**Comment by danchom** [comment]
The trigger does not have access to anything except to its source (i.e. the handler of evet trigger knows only about the event which was fired) and if the message is trigger type driven it will be base only to this trigger. 
When it is action type driven the pattern of the message has access to outputs of all triggers and actions of the rule. 
In the future you can have adding or average actions and result of these actions can be part of the message.

**Comment by smhgit** [comment]
Please note that my suggestion is to add the information to the trigger type not to the trigger. The Trigger will not do anything with the pattern. The action will take the pattern from the TriggerType and will replace the ingredients withe the relevant outputs.

E.g.:

{  
     "uid":"ItemStateChangeTrigger",
     "label":"Item State Trigger",
     "description":"This triggers a rule if an items state changed",
     "configDescriptions":[  
        {  
           "name":"itemName",
           "type":"TEXT",
           "context":"item",
           "label":"item name",
           "description":"the name of the item which's state change should be observed",
           "required":true
        }
     ],
    "pattern":[
        {
            "label": "subject"
            "value": "{{itemName}} change notification"
        },
        {
            "label": "body"
            "value": "{{itemName}} has just change to on"
        }
    ]

**Comment by kaikreuzer** [comment]
> we will have two actions:
> "MessageAction"
> MailAction

I still do not get the problem. Why not have simply the MailAction with a "message" configuration property, which you can fill for your rule with "{{t1.event.itemName}} changed to {{t1.event.itemState}}"?

It absolutely does not make any sense to me to define mail related properties within trigger (types).

**Comment by smhgit** [comment]
Lets assume we have two triggers:
1. Item state change trigger - triggers when the item has change state.
2. Day time trigger - triggers on Sunday

In both cases I want to send an email. What will be the message?

For trigger 1 - Item has changed.
For trigger 2 - Today is Sunday.

As you can see the message depends on the trigger, not on the action!

Am I missing something here?

**Comment by kaikreuzer** [comment]
Very simple: These are two different rules. But imho rules aren't the best way to deal with notifications.
So you might rather want to look for the notification infrastructure under discussion at https://bugs.eclipse.org/bugs/show_bug.cgi?id=434010 andhttps://github.com/eclipse/smarthome/pull/459.

**Comment by smhgit** [comment]
They are two different rules but the action type is the same (thus the action handler is the same)! Notification will not help here as again, I don't  know what was the trigger ...
If I want to give the user predefined messages I need to get it from the trigger (IMHO this is the preferred option) or to have a code in the action the identify the trigger and set the default appropriate message.

I will check if I can do it by identifying the trigger type in the action.

**Comment by kaikreuzer** [comment]
> but the action type is the same

The configuration parameters are on the action, not the action type. So you have two different configurations for both of your rules.

**Comment by smhgit** [comment]
That is correct but I don't want the user to type the message. I want to give him default message, same as IFTTT (and if he wants he can change it)

For that I need to set default value in the action type, but I cannot set it as there is more than one option (trigger depended)

default ==> The default value of the configuration parameter (optional).

Mail action configuration example:

"configDescriptions": [
        {
          "name": "to",
          "type": "TEXT",
          "label": "To",
          "description": "Recipient email address",
          "required": true
        },
        {
          "name": "subject",
          "type": "TEXT",
          "label": "Subject",
          "description": "Email subject",
          "required": true
          "default": ????????????????????????????????
        },
        {
          "name": "message",
          "type": "TEXT",
          "label": "Message",
          "description": "Email message"
          "default": ????????????????????????????????
        }
      ]

**Comment by kaikreuzer** [comment]
> That is correct but I don't want the user to type the message. I want to give him default message, same as IFTTT (and if he wants he can change it)

Here we are talking about a rule template, which does exactly this (and corresponds to an IFTTT recipe).

**Comment by dnobel** [comment]
@smhgit Do you agree?

**Comment by smhgit** [comment]
I currently don't use the templates so I cannot comment. I still think that there is an issue when you don't use templates (which is a valid way to use the rules) but maybe from your side it is not important at this stage.

**Comment by kaikreuzer** [comment]
Let's assume that templates solve the issue and I therefore close this issue.
