### ISSUE TITLE
Change / add lables in module definition

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#204]
As the UI shows the lable information, is is possible to add / change some of the fields in the module JSON files?
1. Change "label":"ItemName", ==> "label":"Item Name",
2. Add "label":"Item Name" to all configurations (E.g., ItemStateCondition).
3. Change "label":"ItemPostCommandAction" ==> "label":"Post command to an item",

(Probably it is not high priority)

**Comment by danchom** [comment]
1) You can create a composite types with predefined label values.
2) You can change the name of the label, description and etc. of the rule, in following way: 
2.1) get the rule from rule registry
2.2) get the module from the rule
2.3) update the module definition 
2.4) update the rule through the rule registry
3) May be we have to extract methods in the rule registry for easier update of module's information which does not change behavior of the rule (such labels, descriptions).

**Comment by smhgit** [comment]
Yordan,

What you referring was how to change it dynamically. I just think that the the current values in the JSON module file should be changed.

**Comment by dnobel** [comment]
Yes I agree, they should be changed.
