### ISSUE TITLE
Rule Category

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#209]
I want to be able to categorizes the modules when presented in the UI. I assume I can use the tag of the module for that but is there another way for that? Something like category field?

**Comment by danchom** [comment]
IMHO tag is enough. You can put more then one tag to a  module and you have rule's methods getByTag() and  getByTags()

**Comment by smhgit** [comment]
The issue with tag is that it is to general and you find out in the end that you have fields which are better be specific.

If category is needed, why not to add it as a field (same as category in Item class)?

**Comment by danchom** [comment]
I think the category is corner case of tag and it duplicates them

**Comment by smhgit** [comment]
In that case, can you consider expanding the tag and built it as Key / Value (Hash of String, String ?)? This way it will be easier to use, otherwise parsing will be needed:

"category:time"

vs

"category", "time"

**Comment by danchom** [comment]
It can't be map because the matching will be too complex. Why don't you set only "time" as a tag? You can call for example ModuleTypeRegistry.getByTag("time") to get all types related to time

**Comment by smhgit** [comment]
My concern is that the I am going to use tags for other purposes and this can create some conflicts.

In any case I will try to use as you suggested hopefully it will be OK.

**Comment by smhgit** [comment]
BTW, I need to get all module type from specific class (e.g., TriggerType) which have a specific tag. Currently there is no explicit method for it. 

I have raised this issue before in the forum and adding something like predicate could help in this cases.

**Comment by danchom** [comment]
At the moment there is no direct method for this and I'm not sure if it is needed.
I can propose you to use different tags for them: triggerTime and actionTime. If you want to list all the time types you can use the method: 
getByTags(new String[]{"triggerTime","actionTime"})

**Comment by smhgit** [comment]
Thx, I will go with this suggestion
