### ISSUE TITLE
Rule add module method

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#211]
Currently (AFAICS) there is no explicit way to add module to a rule. You need to get the Triggers/Conditions/Actions and then add it.

rule.getTriggers().add(module)

Wouldn't it make sense to add a method that will add module to a rule (you already have getModule)?

public void addModule(Module module) {
    if (module instanceof TriggerType {
        getTriggers().add(module)
    } else ...
}

This is useful if you build a rule dynamically.

Is there other way to do it?

**Comment by kaikreuzer** [comment]
You usually also want to decide the position in the list the module should go to (while it does not necessarily have an impact for triggers and conditions at runtime, it definitely makes a difference for actions). Also for the UI you want the order to be respected. So I thing having getters for the lists of the 3 types is fine. It really makes it more specific what you are doing. You can still do the helper logic you ask for in an external utility class, I don't see the need to have it in the bean itself.
