### ISSUE TITLE
Template config issue

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#212]
I have defined a template which uses a condition with children (See below). I was expecting that I will not need to add the configuration parameters to the "if" at it is already defined in the condition itself. but I get the error "Module is not well configured: ...." if I not add the configuration. Is it the way it should be (meaning do I need to add the config block to the template)?
# The template IF (as I was expecting):

 "if": [
      {
        "id": "if",
        "type": "ItemStateOnCondition"
      }
    ],
# The template IF (which is working):

 "if": [
      {
        "id": "if",
        "type": "ItemStateOnCondition",
        "config": {
          "operator": "=",
          "itemName": "$itemName",
          "state": "ON"
        }
      }
    ],
# The condition:

"conditions": [
    {
      "uid": "ItemStateOnCondition",
      "label": "Switch on",
      "description": "Switch state is on",
      "tags":[
        "conditionItem"
      ],
      "children": [
        {
          "id": "itemStateConditionID",
          "type": "ItemStateCondition",
          "config": {
            "itemName": "$itemName",
            "state": "ON",
            "operator": "="
          }
        }
      ],
      "inputs": [
        {
          "name": "itemName",
          "type": "TEXT",
          "label": "Item Name",
          "description": "The item name",
          "required": true
        }
      ]
    },

**Comment by adimova** [comment]
Hi, you still don't have the correct template configuration. It should be:
{
"uid":"Template UID",
"label":"Template Label",
"config":{
"itemName": {
"type": "TEXT",
"label": "Item Name",
"description": "The item name",
"required": true
},
"on":{
...
},
"if": [
{
"id": "if",
"type": "ItemStateOnCondition",
"config": {
"item": "$itemName"
}
}
}
],
"then":{
...
}
}

the condition should be:
"conditions": [
{
"uid": "ItemStateOnCondition",
"label": "Switch on",
"description": "Switch state is on",
"tags":[
"conditionItem"
],
"children": [
{
"id": "itemStateConditionID",
"type": "ItemStateCondition",
"config": {
"item": {
"type": "TEXT",
"label": "Item Name",
"description": "The item name",
"required": true
},
"state": "ON",
"operator": "="
}
}
],
"inputs": [
{
"name": "itemState",
"type": "java.lang.String",
"label": "Item State",
"description": "The item state",
"reference":"$item.state",
"required": true
}
]
},

**Comment by smhgit** [comment]
Thx, I will check my JSON files again and will return with an answer.

**Comment by kaikreuzer** [comment]
ok, feel free to re-open this issue if the answer is that there is some problem :-)
