### ISSUE TITLE
Change visibility enumeration to "hidden", "expert", "visible"

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#214]
We should use better suited vocabulary than public and private for the visibility of module types and templates. As discussed "hidden", "expert", "visible" could be appropriate options.
I'd also suggest to add visibility fields to rules and modules, would you agree?

**Comment by danchom** [comment]
I'm not sure if it is right to hide modules participating into a rule, because the modules are connected to each other and if we hide some of them, the logic of the rule will not be clear. 
For visibility of rules it is ok for me.

**Comment by kaikreuzer** [comment]
Ok, no visibility for modules then, only for module types, templates and rules.
