### ISSUE TITLE
Is the guava dependence is needed?

### ISSUE THREAD

**Issue by danchom** [marinmitev/smarthome#230]
The com.google.guava is too fat (2MB) and it export collections. Is it possible to use java collections instead of guava ones?
It is used in:
RuleEventFactory
AbstractManagedProvider
AbstractRegistry
AbstractEventFactory
AbstractTypedEventSubscriber

**Comment by kaikreuzer** [comment]
Yes, we should remove it from RuleEventFactory indeed.
We won't change the classes outside of the automation component, though. As discussed, you should have your own implementation for your product integration, since the ESH classes would anyhow infer many other unwanted dependencies as well.

**Comment by hristostanchev** [comment]
This is OK for us. We can change the classes outside of automation component.
