### ISSUE TITLE
Add swagger annotations to rule rest resources

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#234]
In order to document the rest api, swagger annotations should be added to the rest resources.

**Comment by kaikreuzer** [comment]
See e.g. https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.core/src/main/java/org/eclipse/smarthome/io/rest/core/item/ItemResource.java#L209 as a reference how swagger annotations look like for other ESH resources.

**Comment by egramatova** [comment]
I would recommend that you use the new swagger annotations which come as javadoc tags, thus no additional compile-time or run-time dependencies are needed. In my opinion the javadoc tags are much more user-friendly and flexible, furthermore I believe they provide more options for customizing the generated REST API documentation. 

Please see https://github.com/teamcarma/swagger-jaxrs-doclet

**Comment by kaikreuzer** [comment]
> use the new swagger annotations

They do not seem to be anything official by Swagger?
The official annotations are the ones we are using: https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X.

**Comment by egramatova** [comment]
Indeed, instead of using “pure” swagger, which requires its own annotations and dependencies, we use swagger-jaxrs-doclet that is based on javadoc (including custom tags) and leverages JAX-RS annotations. It seems that the doclet that we are using generates swagger 1.2 complaint REST API documentation, but I have not seen any disadvantage in that so far.

**Comment by egramatova** [comment]
In addition, there are other REST API documentation tools (such as http://www.miredot.com/) that generate the API documentation based on javadoc and JAX-RS/JAXB annotations which seems to be more flexible approach.

**Comment by kaikreuzer** [comment]
Implemented with https://github.com/marinmitev/smarthome/pull/254.
Thanks!
