### ISSUE TITLE
NPE when using gson parser

### ISSUE THREAD

**Issue by smhgit** [marinmitev/smarthome#252]
I've changed to GSON parser and I get NPE in several places. It seems that with the GSON parser not all fields are initialized.

Is it correct?

An example - RuntimeRule: configParameter.isMultiple() is null

```
private void checkType(Object configValue, ConfigDescriptionParameter configParameter) {
    Type type = configParameter.getType();
    if (configParameter.isMultiple()) {
```

**Comment by danchom** [comment]
IMHO ConfigDescriptionParameter.isMultiple() has to be changed to return non null value (as usual in ESH project). There are other methods which have to be fixed too i.e. isReadOnly(), getMultipleLimit(), isRequired(), getLimitToOptions(), isAdvanced()

**Comment by kaikreuzer** [comment]
Not an issue of the automation component itself, so I created https://bugs.eclipse.org/bugs/show_bug.cgi?id=482684.
