### ISSUE TITLE
Allow adding rules with externally provided UID

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#30]
- RuleRegistry should only add a UID to a newly added rule, if none was provided.
- The BundleResourceRuleImporter should add a UID to the imported rules that is derived from bundle id, version and rule name, so that it is constructed the same way every time.
- The JSON parser must support the UID property on rules.

**Comment by adimova** [comment]
How to proceed the BundleResourceRuleImporter when json file contains a value for property "uid":
What will be the generated Rule UID then?
What to do if a rule with the same ID exists and the proposed ID is not unique anymore?

**Comment by kaikreuzer** [comment]
> What will be the generated Rule UID then?

No generated one, the one from JSON should be used.

> What to do if a rule with the same ID exists and the proposed ID is not unique anymore?

Do not import, log a warning.

**Comment by kaikreuzer** [comment]
Implemented through #54
