### ISSUE TITLE
Localization through I18NProvider

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#32]
The current Localizer class should be replaced by using the I18NProvider interface, so that a localization implementation can be plugged in (for ESH in place already).

**Comment by dnobel** [comment]
Code for I18NUtil: https://github.com/eclipse/smarthome/blob/8078ab2d0f8da486563dc03df71e87efa7e8a277/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/i18n/ThingTypeI18nUtil.java

**Comment by dnobel** [comment]
what you can see there is the inference of a key based on the given context. it first looks up if it is constant and if not it infers the default keys and does a look up via the I18nProvider. Here you can see the default key schema for binding.xml for example: https://www.eclipse.org/smarthome/documentation/features/internationalization.html

**Comment by dnobel** [comment]
DOne.
