### ISSUE TITLE
Handle enabling/disabling of rules

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#34]
The RuleRegistry must provide methods to get and set rules to enabled/disabled.
If StorageService is available, this information should be persisted in a separate Storage, otherwise it should be kept only in memory.
The "active" property should be removed from the rule JSON format. If a rule should be deactivated, this is done through a separate call to the RuleRegistry.

**Comment by danchom** [comment]
done and merged.
The Benedikt's comment are put into new issue: https://github.com/marinmitev/smarthome/issues/65
