### ISSUE TITLE
Add basic module types

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#37]
The rule engine should come with some basic module type definitions and their handlers, like Item event triggers, thing status triggers, item command actions and item state actions.

**Comment by kaikreuzer** [comment]
As per the design of the rule engine, it makes sense to implement this as generic event module types, w hich have a Java implementation and which can then simply be customized to more specific module types through additional JSON definitions (e.g. providing an event type or topic id as a parameter). This is also how the sample module type handler shows exemplarily.

**Comment by dnobel** [comment]
Depends on the implementation of #64

**Comment by kaikreuzer** [comment]
> Depends on the implementation of #64

Not correct, only needs customized module types, which is in place.
