### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#38]
The new rule engine contribution must come with documentation
- explaining the overall concepts/ideas
- listing the ways for interaction (bundle resources, console, Java API, etc.)
- showing the JSON syntax (incl. reference to the JSON schema)
- providing examples for JSON as well as code

**Comment by kaikreuzer** [comment]
Note: the org.eclipse.smarthome.automation.json bundle should be removed in this context.

**Comment by dnobel** [comment]
Skeleton will be provided by DTAG by end of this week.
