### ISSUE TITLE
Resolving of ModuleTypeRegistry by AbstractModuleHandler

### ISSUE THREAD

**Issue by BenediktNiehues** [marinmitev/smarthome#48]
The AbstractModuleHandler should resolve the ModuleTypeRegistry by itself during initialization. This reduces the overhead in the common implementations and makes the abstract method getModuleTypeRegistry obsolete.

**Comment by kaikreuzer** [comment]
I understand the concern of too many service trackers, if the handlers themselves deal with resolving the ModuleTypeRegistry.
Another option is to do the tracking only in the BaseModuleHandlerFactory (see https://github.com/marinmitev/smarthome/issues/49) and have it injected into the ModuleHanders (possibly directly in the constructor)? Anyhow, some place needs to keep track of the Handlers and dispose them when their HandlerFactory or the ModuleTypeRegistry disappears. This place could also deal with injecting the ModuleTypeRegistry in the handlers. As we do not treat the handlers as OSGi services on their own, I think this procedure would make more sense than having an internal service tracker per handler.

**Comment by danchom** [comment]
will be done
