### ISSUE TITLE
BasicModuleHandlerFactory

### ISSUE THREAD

**Issue by BenediktNiehues** [marinmitev/smarthome#49]
Move the BasicModuleHandlerFactory to the api Bundle and provide methods for common useCases here. According to Issue #48 the setter and unsetter could probably be removed as the ModuleTypeRegistry is resolved in the Handlers themselves. 
Additionally the BasicModuleHandlerFactory should be able to control the lifecycle of the created ModuleHandlers.

**Comment by kaikreuzer** [comment]
I assume you mean BaseModuleHandlerFactory, in accordance with the BaseThingHandlerFactory.

**Comment by danchom** [comment]
Will be done.
