### ISSUE TITLE
Fullfill coding guidelines

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#51]
Check all code to comply with https://www.eclipse.org/smarthome/documentation/development/guidelines.html.

**Comment by dnobel** [comment]
Discuss internal package naming.

**Comment by danchom** [comment]
We agreed with Kai to rename impl package names to intern.

**Comment by dnobel** [comment]
OK, thanks. But I hope you meant "internal" ;)

**Comment by danchom** [comment]
Unfortunately the ".impl." packages are disappeared and at the moment we can't do difference between public api classes and internal implementation classed. Isn't be better to add internal into implementation packages again? For example: org.eclipse.smarthome.automation.core -> org.eclipse.smarthome.automation.internal.core

**Comment by hristostanchev** [comment]
The internal package will be added after integration of composite module support.

**Comment by marinmitev** [comment]
link to previous Kai's comment about coding guidelines
https://github.com/eclipse/smarthome/pull/317#issuecomment-126260989
