### ISSUE TITLE
Agree on format for context parameter of ConfigDescriptionParameter

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#55]
See discussion at https://github.com/marinmitev/smarthome/pull/54#discussion_r37056126.

I don't think that introducing an API interface (Converter) with pluggable services is the right choice for for this requirement.

**Comment by danchom** [comment]
We have decided to use JSON in context field, because in this way we can add additional fields to ConfigDescriptionParameter without changing its interface.

**Comment by danchom** [comment]
The Converter interface will be removed. The fixed custom syntax will be added for context field. For example: context: "(key=value, key1=value1, key3=(a=b, c=d))"
