### ISSUE TITLE
Improve Rule UID generation in RuleResourceBundleImporter

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#57]
The RuleResourceBundleImporter.setUID() method has the following problems that should be addressed:
- it uses the bundle id (vendor id), which can potentially change if a bundle is uninstalled and re-installed. Using the bundle name would imho be a better choice.
- `rulesCount` is declared static and will be incremented globally. This means that rules will get different UIDs if the startup order of bundle changes or a bundle in uninstalled. The count should instead be done individually per processed bundle.
- The rule name could potentially contain special characters that we would not want to have within the UID (which will e.g. be used as part of a URL in the REST API). We should therefore strip out any characters that we consider illegal for the UID.

**Comment by danchom** [comment]
We propose UID=bundle symbolic name(where . is replaced with _) + number.
The counter will not be global. 
We have to define valid symbols in rule uid, because it can be set by the user.

**Comment by dnobel** [comment]
The valid set of characters for other UIDs is: [A-Za-z0-9_-]\* of course seperated by ":"

**Comment by danchom** [comment]
done and merged!
