### ISSUE TITLE
Parser API should be refactored

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#59]
The current API of the Parser imho does not make sense, especially the Status class.

My suggestion is to:
- change the Parser.importData() method to return a Set of RuleDTOs or throw a ParsingException with a  list of errors (like Status.errorMap)
- remove the Status class completely (and introduce the ParsingException instead)

**Comment by danchom** [comment]
I'm not sure about that. If the importer can import half of rules and fails on the others, what should the parser do? 
1) Import the half of them and return status object containing description of operation - current implementation 
2) Import the half of them and throws exception - in this way it is not clean why there are imported rules when the operation is failed
3) just failed and don't import anything

**Comment by dnobel** [comment]
Does it have to return the parsing status at all? Wouldn´t it be sufficient to just log what failed to import?

**Comment by dnobel** [comment]
Will be discussed with Hristo and Kai

**Comment by kaikreuzer** [comment]
Do you really want to wait so long? Fine for me to discuss here on Github.
My take on this is that if somebody expects that a JSON construct should be imported independently from others, he should put it in a separate file. Whatever comes within the same file, it is ok for me to reject all of its content if some module in it is not parseable. It is probably the even more expected behavior than ending up with parts of the file being imported while others are dismissed.

**Comment by dnobel** [comment]
Decision must be made:
- Import always all rules, even if some rules failed to be imported
- Stop importing rules if one rule failed to be imported
- Make it configurable if all rules should be imported or not

In addition we need to decide:
- Throwing an Exception
- Returning a status object

Will be decided next week.

**Comment by hristostanchev** [comment]
We agree that if there is a problem with one or more rules import will fail and nothing will be imported. The exception (status will be removed) will be thrown with info which are the problem rules. This is related also to module types and rule templates importing. Ani will handle it next week.

**Comment by adimova** [comment]
In current situation the parser do not import or export anything, only parses data, so my suggestion is to change the method names as follow:
importData -> parseData
exportData -> transformObjects
are you agree with this proposal?

**Comment by kaikreuzer** [comment]
How about simply calling them "parse" and "transform"?

**Comment by adimova** [comment]
For me "parse" is clear and simple, but "transform" can be replaced by other, more meaningful word if someone can offer any, i can't. May be "convert" or "translate".

**Comment by kaikreuzer** [comment]
serialize?

**Comment by marinmitev** [comment]
one more vote for 'serialize'

**Comment by adimova** [comment]
I also like it (serialize)

**Comment by kaikreuzer** [comment]
I just noticed that although https://github.com/marinmitev/smarthome/pull/97 has been merged, the code didn't make it into the branch - it is still the old there.
@adimova, Could you please check and try creating a new PR with your changes?
