### ISSUE TITLE
gson dependency in events

### ISSUE THREAD

**Issue by marinmitev** [marinmitev/smarthome#81]
In the package org.eclipse.smarthome.core.events;
there is a class AbstractEventFactory with dependency to com.google.gson.Gson;
this dependency should be moved outside this class

**Comment by hristostanchev** [comment]
ProSyst can reimplement the AbstractEventFactory and remove Gson dependancy. Or we can implement the EventFactory interface class. ProSyst recheck and issue can be closed.
