### ISSUE TITLE
When removing RuleProviders the corresponding rules should be removed from RuleRegistry

### ISSUE THREAD

**Issue by BenediktNiehues** [marinmitev/smarthome#84]
The IntegrationTest "assert that a rule can be added by a ruleProvider" fails because when removing the ruleProvider the rules still exist in RuleRegistry. Expected is that the rules which are created by this RuleProvider are removed from the RuleRegistry as well.

**Comment by danchom** [comment]
I'm not sure about that. The RuleProvider is not common provider, it is only an importer. As I remember there was discussion that the rule must continue to work independent of provider. The rule can be removed only manually from RuleRegistry.removeRule(String Id)

**Comment by kaikreuzer** [comment]
No, that's a wrong memory :-)
removeRule will only work for the ManagedRuleProvider; all rules that are imported are using this.
If somebody decides to add a RuleProvider, these rules are considered to be static and read-only and only existent as long as the provider is there.

**Comment by dnobel** [comment]
FIxed.
